version: '3.7'
name: "garraiomapairekia"
services:
  server:
    container_name: "server"
    build: "./server"
    restart: "always"
    env_file: mongodb/server.env
    volumes:
      - ./config.json:/server/config.json
      - ./feeds.json:/server/feeds.json
      - server_zip:/server/zip
      - server_gtfs:/server/gtfs
      - server_geojson:/server/geojson
      - martin_tiles:/server/tiles
      - otp_gtfs:/server/otp_gtfs
      - /var/run/docker.sock:/var/run/docker.sock # Para poder acceder a docker desde dentro del contenedor
    networks:
      - red_interna
    depends_on:
      - mongodb
      - martin
  nginx:
    image: "nginx:1.25-alpine"
    container_name: "nginx"
    restart: "always"
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./nginx/nginx-ip.conf:/etc/nginx/nginx.conf
    depends_on:
      - martin
      - api
      - web-app
    networks:
      - red_interna
  martin:
    container_name: "martin"
    command: "-c /etc/martin/config.yaml"
    image: "ghcr.io/maplibre/martin:v0.13.0"
    restart: "always"
    expose:
      - "80"
    volumes:
      - ./martin/config.yaml:/etc/martin/config.yaml
      - "martin_tiles:/tiles"
    networks:
      - red_interna
  mongodb:
    container_name: "mongodb"
    image: "mongodb/mongodb-community-server:7.0-ubuntu2204"
    expose:
      - "27017"
    restart: "always"
    env_file:
      - mongodb/root.env
      - mongodb/server.env
      - mongodb/api.env
    volumes:
      - mongodatabase:/data/db
      - ./mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - red_interna
  api:
    container_name: "api"
    build: "./api"
    restart: "always"
    env_file: mongodb/api.env
    expose:
      - "80"
    networks:
      - red_interna
    depends_on:
      - mongodb
  web-app:
    container_name: "webapp"
    build: "./web"
    restart: "always"
    expose:
      - "80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - red_interna
  opentripplanner:
    container_name: "opentripplanner"
    image: docker.io/opentripplanner/opentripplanner:2.5.0_2024-01-11T16-12
    expose:
      - "8080"
    restart: "always"
    volumes:
      - ./otp/build-config.json:/var/opentripplanner/build-config.json:ro
      - ./otp/init-otp.sh:/var/garraiomapairekia/init-otp.sh:ro
      - ./osm:/var/garraiomapairekia/osm:ro
      - otp_gtfs:/var/garraiomapairekia/gtfs:ro
      - otp_graphs:/var/garraiomapairekia/graphs:rw
    networks:
      - red_interna
    entrypoint: bash /var/garraiomapairekia/init-otp.sh
volumes:
  mongodatabase:
    name: mongodatabase
  martin_tiles:
    name: martin_tiles
  server_zip:
    name: server_zip
  server_gtfs:
    name: server_gtfs
  server_geojson:
    name: server_geojson
  otp_gtfs:
    name: otp_gtfs
  otp_graphs:
    name: otp_graphs
networks:
  red_interna:
    driver: bridge